Trigger aggregator update signal
open-craft/openedx-completion-aggregator pull request #186
Opened 2024-02-13 10:01 UTC by qasimgulzar

2024-02-15 09:16 UTC, qasimgulzar commented
@open-craft-grove could you please help reviewing this PR

2024-02-15 12:03 UTC, Agrendalath requested changes
@qasimgulzar, is there a specific reason for using plain signals instead of [openedx-events](https://github.com/openedx/openedx-events)?

2024-02-15 12:03 UTC, Agrendalath commented on completion_aggregator/models.py
> +            AggregatorUpdate.send(sender=self.__class__, aggregation_data=aggregation_data)
Isn't `aggregation_data` undefined when `connection.vendor == 'sqlite'`?

2026-03-31 22:32 UTC, samuelallan72 commented
@qasimgulzar I'll close this PR since it appears to be stale. Feel free to reopen if it's still relevant.

2026-03-31 22:32 UTC, closed without merging